export const DUMMY_CHARACTERS = [
  {
    id: 1,
    name: 'Celest',
    player: 'Maja',
    job: 'photograph',
    age: 28,
    stats: [
      { statName: 'str', value: 70 },
      { statName: 'con', value: 50 },
      { statName: 'siz', value: 50 },
      { statName: 'dex', value: 60 },
      { statName: 'app', value: 55 },
      { statName: 'int', value: 75 },
      { statName: 'pow', value: 49 },
      { statName: 'edu', value: 82 },
      { statName: 'speed', value: 9 },
    ],
  },
  {
    id: 2,
    name: 'Marie',
    player: 'Marta',
    job: 'nurse',
    age: 24,
    stats: [
      { statName: 'str', value: 50 },
      { statName: 'con', value: 65 },
      { statName: 'siz', value: 45 },
      { statName: 'dex', value: 75 },
      { statName: 'app', value: 55 },
      { statName: 'int', value: 75 },
      { statName: 'pow', value: 70 },
      { statName: 'edu', value: 85 },
      { statName: 'speed', value: 7 },
    ],
  },
  {
    id: 3,
    name: 'Ricky',
    player: 'Daniel',
    job: 'security',
    age: 32,
    stats: [
      { statName: 'str', value: 90 },
      { statName: 'con', value: 80 },
      { statName: 'siz', value: 85 },
      { statName: 'dex', value: 70 },
      { statName: 'app', value: 45 },
      { statName: 'int', value: 50 },
      { statName: 'pow', value: 60 },
      { statName: 'edu', value: 40 },
      { statName: 'speed', value: 11 },
    ],
  },
  {
    id: 4,
    name: 'Leopold',
    player: 'Zbychu',
    job: 'archeology',
    age: 36,
    stats: [
      { statName: 'str', value: 70 },
      { statName: 'con', value: 50 },
      { statName: 'siz', value: 50 },
      { statName: 'dex', value: 60 },
      { statName: 'app', value: 55 },
      { statName: 'int', value: 75 },
      { statName: 'pow', value: 49 },
      { statName: 'edu', value: 82 },
      { statName: 'speed', value: 9 },
    ],
  },
  {
    id: 5,
    name: 'John',
    player: 'Janek',
    job: '-',
    age: 27,
    stats: [
      { statName: 'str', value: 70 },
      { statName: 'con', value: 50 },
      { statName: 'siz', value: 50 },
      { statName: 'dex', value: 60 },
      { statName: 'app', value: 55 },
      { statName: 'int', value: 75 },
      { statName: 'pow', value: 49 },
      { statName: 'edu', value: 82 },
      { statName: 'speed', value: 9 },
    ],
  },
];
